services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
      - ./npm-data/auth/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - arksrv-network

  arksrv-site:
    image: 'nginx:alpine'
    container_name: arksrv_website
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./arksrv/html:/usr/share/nginx/html
      - ./arksrv/nginx-conf:/etc/nginx/conf.d
    networks:
      - arksrv-network

  php-fpm:
    image: 'php:8.2-fpm-alpine'
    container_name: arksrv_php
    restart: unless-stopped
    volumes:
      - ./arksrv/html:/usr/share/nginx/html
    networks:
      - arksrv-network

networks:
  arksrv-network:
    driver: bridge
