networks:
  arksrv-network:
    name: arksrv-network

services:
  # 1. خادم إدارة التوجيه وشهادات الأمان (Nginx Proxy Manager)
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'   # منفذ الويب العادي
      - '443:443' # منفذ الويب الآمن المشفر
      - '81:81'   # منفذ لوحة التحكم الخاصة بك
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - arksrv-network

  # 2. حاوية موقعك الشخصي ARKsrv (معزولة ومحمية داخلياً)
  arksrv-site:
    image: 'nginx:alpine'
    container_name: arksrv_website
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./arksrv/html:/usr/share/nginx/html
    networks:
      - arksrv-network
